"""add image to box model

Revision ID: 4e36e69ff6a0
Revises: 2b07396d7239
Create Date: 2024-03-06 11:52:29.748869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e36e69ff6a0'
down_revision = '2b07396d7239'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('box', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('box', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
